#!/bin/bash
read -p "title: " Title
read -p "contentType: " ContentType
#read -p "file to copy: " OrigFile
#OrigFileFull=~/Documents/stories/$OrigFile
shortDate=$(date "+%Y-%m-%d")
longDate=$(date "+%Y-%m-%d %H:%M:%S" )
filePath=~/Documents/nblancard/blancard.github.io/_posts/
slug=${Title// /-}
filename=$filePath/$shortDate-$slug.markdown
touch $filename
echo "---" >> $filename
echo "layout: post" >> $filename
echo "title: "$Title >> $filename
echo "date: "$longDate >> $filename
echo "categories: "$ContentType >> $filename
echo "contentType: "$ContentType >> $filename
echo "---" >> $filename
echo "" >> $filename
if [[ $ContentType = "music" ]]; then
  read -p "youtube Url: " yUrl
  echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/'$yUrl'" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>' >> $filename
fi
vim $filename
